### ISSUE TITLE
Error Json: cannot unmarshal number 

### ISSUE THREAD

**Issue by ste-ta** [kgbvax/wolfmqttbridge#1]
Hi,

thanks for the development. I wanted to use your code for an integration into FHEM via MQTT. It worked "almost" perfect for me. However, I got various errors with my Wolf CGS2L:
ERRO[0003] json: cannot unmarshal number 18000500001 into Go struct field ParameterDescriptor.ParameterId of type int

I will create a pull request for this and change the ints to int64 which fixed the issue for me.

**Comment by kgbvax** [comment]
Thanks for the PR & I am glad that you found it useful.
